title: mxclover
author: mxclover
description: personal blog
disqus_shortname: mxclover
highlighter: null
permalink: /:year/:month/:day/:title/

url: 
baseurl:

links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: GitHub
    url: http://github.com/mxclover